### ISSUE TITLE
Add sample scene

### ISSUE THREAD

**Issue by vfqd** [Brian-Jiang/SmartReference#3]
Hi Brian, this is a cool project! I've been trying to set it up locally without much success. I think it would be great if you added a sample to the repo with correct initialization etc to show how you intend things to work.

**Comment by Brian-Jiang** [comment]
Thank you! Sure, I do have a demo but I upload it to asset store and forgot it here. I'll upload it some time next week

**Comment by vfqd** [comment]
The asset store sample scene seems to just be an empty unity scene if that helps!

**Comment by Brian-Jiang** [comment]
#4 Added the sample from asset store, you can check profiles folder for reference, I'll add more samples in scene later
